"""Mapeo PRODUCTO -> (fam_esp, segmento, segmento_2).

Generado de Producto-Segmento.xlsx (tabla que mantiene Marco a mano).
Excluye FRUTA FRESCA (este reporte es INDUSTRIA). Vacios quedan como None.
- segmento:   eje NOP / Convencional / UE
- segmento_2: segmento del reporte (ACEITE, JUGO CONCENTRADO, FIBRA, ...)
"""

# PRODUCTO: (fam_esp, segmento, segmento_2)
PRODUCTO_SEGMENTO = {
    'Aceite Esencial de Limón NOP T180 Kg': ('ACEITE LIMON', 'NOP', 'ACEITE'),
    'Aceite Esencial de Limón T180 Kg': ('ACEITE LIMON', 'Convencional', 'ACEITE'),
    'Aceite Esencial de Naranja Agria T180 Kg': ('ACEITE NARANJA AGRIA', 'Convencional', 'ACEITE'),
    'Aceite Esencial de Naranja T180 Kg': ('ACEITE NARANJA', 'Convencional', 'ACEITE'),
    'Aceite Esencial de Pomelo P T180 Kg': ('ACEITE POMELO ROSADO', 'Convencional', 'ACEITE'),
    'Aceite Esencial de Pomelo W T180 Kg': ('ACEITE POMELO BLANCO', 'Convencional', 'ACEITE'),
    'Cáscara Deshidratada de Limón B20 Kg': ('CASCARA LIMON - A', 'Convencional', 'CASCARA'),
    'Cáscara Deshidratada de Limón B50 PA': ('CASCARA LIMON - A', 'Convencional', 'CASCARA'),
    'Cáscara Deshidratada de Limón B50 PB': ('CASCARA LIMON - B', 'Convencional', 'FIBRA'),
    'Cáscara Deshidratada de Limón BFG 20 Kg': ('BFG', 'Convencional', 'FIBRA'),
    'Cáscara Deshidratada de Limón CF-1 20 Kg': ('CF-1 LIMON', 'Convencional', 'FIBRA'),
    'Cáscara Deshidratada de Limón LF-19 20 Kg': ('LF-19 LIMON', 'Convencional', 'FIBRA'),
    'Cáscara Deshidratada de Naranja B50 PA': ('CASCARA NARANJA - A', 'Convencional', 'CASCARA'),
    'Cáscara Deshidratada de Naranja B50 PB': ('CASCARA NARANJA - B', 'Convencional', 'FIBRA'),
    'Esencia de Limón Fase Oleosa T180 Kg': ('ESENCIA LIMON', 'Convencional', 'ACEITE'),
    'Jugo Clarificado de Limón 400 Gpl T250 Kg': ('JUGO LIMON 400 GPL', 'Convencional', 'JUGO CONCENTRADO'),
    'Jugo Concentrado Clarificado de Limón Alto Bx 200 Gpl T250 Kg': ('JUGO LIMON 200 GPL', 'Convencional', 'JUGO CONCENTRADO'),
    'Jugo Concentrado de Limón 400 Gpl B1400 Kg': ('JUGO LIMON 400 GPL', 'Convencional', 'JUGO CONCENTRADO'),
    'Jugo Concentrado de Limón 400 Gpl T250 Kg': ('JUGO LIMON 400 GPL', 'Convencional', 'JUGO CONCENTRADO'),
    'Jugo Concentrado de Limón 400 GPL TP 250 Kg': ('JUGO LIMON 400 GPL', 'Convencional', 'JUGO CONCENTRADO'),
    'Jugo Concentrado de Limón 500 Gpl B1390 Kg': ('JUGO LIMON 500 GPL', 'Convencional', 'JUGO CONCENTRADO'),
    'Jugo Concentrado de Limón 500 Gpl T260 Kg': ('JUGO LIMON 500 GPL', 'Convencional', 'JUGO CONCENTRADO'),
    'Jugo Concentrado de Limón NOP 400 Gpl B24,5 Kg': ('JUGO LIMON 400 GPL', 'NOP', 'JUGO CONCENTRADO'),
    'Jugo Concentrado de Limón NOP 400 Gpl T250 Kg': ('JUGO LIMON 400 GPL', 'NOP', 'JUGO CONCENTRADO'),
    'Jugo Concentrado de Limón UE 400 Gpl T250 Kg': ('JUGO LIMON 400 GPL', 'UE', 'JUGO CONCENTRADO'),
    'Jugo Concentrado de Naranja NOP T265 Kg': ('JUGO NARANJA', 'NOP', 'JUGO CONCENTRADO'),
    'Jugo Concentrado de Naranja T265 Kg': ('JUGO NARANJA', 'Convencional', 'JUGO CONCENTRADO'),
    'Jugo Concentrado de Pomelo NOP T260 Kg': ('JUGO POMELO', 'NOP', 'JUGO CONCENTRADO'),
    'Jugo Concentrado Top de Limón T250 Kg': ('JUGO LIMON TOP', 'Convencional', 'JUGO LIMON TOP'),
    'Jugo NFC de Limón B1100 Kg': ('NFC LIMON', 'Convencional', 'NFC'),
    'Jugo NFC de Limón B8000 Lts': ('NFC LIMON', 'Convencional', 'NFC'),
    'Jugo NFC de Limón NOP T195 Kg': ('NFC LIMON', 'NOP', 'NFC'),
    'Jugo NFC de Limón NOP TC 200 Kg': ('NFC LIMON', 'NOP', 'NFC'),
    'Jugo NFC de Limón T195 Kg': ('NFC LIMON', 'Convencional', 'NFC'),
    'Jugo NFC de Limón T200 Kg': ('NFC LIMON', 'Convencional', 'NFC'),
    'xJugo Concentrado de Limón Alto Bx 200 Gpl T250 Kg': ('JUGO LIMON 200 GPL', 'Convencional', 'JUGO CONCENTRADO'),
    'Jugo Concentrado de Limón Alto Bx 200 Gpl T250 Kg': ('JUGO LIMON 200 GPL', 'Convencional', 'JUGO CONCENTRADO'),
    'Jugo Concentrado de Limón 400 Gpl B20 Kg': ('JUGO LIMON 400 GPL', 'Convencional', 'JUGO CONCENTRADO'),
    'Jugo Concentrado de Pomelo T260 Kg': ('JUGO POMELO', 'Convencional', 'JUGO CONCENTRADO'),
    'Pulpa de Limón T180 Kg': ('PULPA LIMON', 'Convencional', 'OTROS'),
    'Pulpa de Naranja T180 Kg': ('PULPA NARANJA', 'Convencional', 'OTROS'),
    'Cáscara Deshidratada de Naranja Agria B50 PA': ('CASCARA NARANJA - A', 'Convencional', 'CASCARA'),
    'Aceite Esencial de Limón B19 Kg': ('ACEITE LIMON', 'Convencional', 'ACEITE'),
    'Jugo Clarificado de Naranja T265 Kg': ('JUGO NARANJA', 'Convencional', 'JUGO CONCENTRADO'),
    'Jugo Clarificado de Pomelo Kg': ('JUGO POMELO', 'Convencional', 'JUGO CONCENTRADO'),
    'Jugo NFC de Naranja T200 Kg': ('NFC NARANJA', 'Convencional', 'NFC'),
    'Jugo NFC de Limón TC 200 Kg': ('NFC LIMON', 'Convencional', 'NFC'),
    'Cáscara Deshidratada de Limón NOP CF-1 50 Kg': ('CF-1 LIMON NOP', 'NOP', 'FIBRA'),
    'Cáscara Deshidratada de Naranja CF-1 50 Kg': ('CF-1 NARANJA', 'Convencional', 'FIBRA'),
    'Jugo Concentrado de Limón 450 Gpl T260 Kg': ('JUGO LIMON 450 GPL', 'Convencional', 'JUGO CONCENTRADO'),
    'Jugo Concentrado de Limón 500 Gpl B25,5 Kg': ('JUGO LIMON 500 GPL', 'Convencional', 'JUGO CONCENTRADO'),
    'Jugo Clarificado de Limón 400 Gpl B24,5 Kg': ('JUGO LIMON 400 GPL', 'Convencional', 'JUGO CONCENTRADO'),
    'Jugo Concentrado de Limón 400 Gpl B8000 Lts': ('JUGO LIMON 400 GPL', 'Convencional', 'JUGO CONCENTRADO'),
    'Jugo Concentrado de Limón NOP 500 Gpl T260 Kg': ('JUGO LIMON 500 GPL', 'NOP', 'JUGO CONCENTRADO'),
    'Jugo Concentrado de Naranja NOP T260 Kg': ('JUGO NARANJA', 'NOP', 'JUGO CONCENTRADO'),
    'Jugo NFC de Naranja NOP T200 Kg': ('NFC NARANJA', 'NOP', 'NFC'),
    'Jugo NFC de Naranja NOP TC 200 Kg': ('NFC NARANJA', 'NOP', 'NFC'),
    'Cáscara Deshidratada de Naranja NOP B50 PB': ('CASCARA NARANJA - B', 'NOP', 'FIBRA'),
    'Esencia de Limón Fase Acuosa T200 Kg': ('ESENCIA LIMON', 'Convencional', 'ACEITE'),
    'Destilado de Limón T180': ('ESENCIA LIMON', 'Convencional', 'ACEITE'),
    'Jugo Concentrado de Naranja Agria T265 Kg': ('JUGO NARANJA AGRIA', 'Convencional', 'JUGO CONCENTRADO'),
    'Jugo NFC de Limón NOP T200 Kg': ('NFC LIMON', 'NOP', 'NFC'),
    'Aceite de Semilla de Limón B20': ('ACEITE SEMILLA LIMON', 'Convencional', 'ACEITE'),
    'Aceite Esencial de Pomelo T180 Kg': ('ACEITE POMELO', 'Convencional', 'ACEITE'),
    'Esencia de Naranja Fase Oleosa T180': ('ESENCIA NARANJA', 'Convencional', 'ACEITE'),
    'Fase Acuosa Pomelo': ('ESENCIA POMELO', 'Convencional', 'ACEITE'),
    'Fase Acuosa Naranja': ('ESENCIA NARANJA', 'Convencional', 'ACEITE'),
    'Fase Acuosa Limón': ('ESENCIA LIMON', 'Convencional', 'ACEITE'),
    'Cáscara Deshidratada de Pomelo B50 PA': ('CASCARA POMELO - A', 'Convencional', 'CASCARA'),
    'Cáscara Deshidratada de Limón NOP B50 PA': ('CASCARA LIMON - A', 'NOP', 'CASCARA'),
    'Cáscara Deshidratada de Limón NOP B50 PB': ('CLD-B LIMON NOP', 'NOP', 'FIBRA'),
    'Cáscara Deshidratada de Naranja NOP B50 PA': ('CASCARA NARANJA - A', 'NOP', 'CASCARA'),
    'Cáscara Deshidratada de Pomelo NOP PA': ('CASCARA POMELO - A', 'NOP', 'CASCARA'),
    'Fibras (BF-1 y HF)': ('HF', 'Convencional', 'FIBRA'),
    'Jugo Concentrado de Naranja T265 Kg NOP': ('JUGO NARANJA', 'NOP', 'JUGO CONCENTRADO'),
    'Jugo NFC de Naranja T195 Kg': ('NFC NARANJA', 'Convencional', 'NFC'),
    'Jugo Concentrado FR de Pomelo T200 Kg': ('JUGO POMELO', 'Convencional', 'JUGO CONCENTRADO'),
    'Jugo NFC de Naranja NOP': ('NFC NARANJA', 'NOP', 'NFC'),
    'Jugo NFC de Pomelo NOP T195 Kg': ('NFC POMELO', 'NOP', 'NFC'),
    'Aceite Esencial de Mandarina T180 Kg': ('ACEITE MANDARINA', 'Convencional', 'ACEITE'),
    'Aceite Esencial de Pomelo P T47 Kg': ('ACEITE POMELO ROSADO', 'Convencional', 'ACEITE'),
    'AE Limon Granel Tk 8100': ('ACEITE LIMON', 'Convencional', 'ACEITE'),
    'AE Limon NOP Granel Tk 8100 SC': ('ACEITE LIMON', 'NOP', 'ACEITE'),
    'AE Naranja Granel Tk 8100': ('ACEITE NARANJA', 'Convencional', 'ACEITE'),
    'AEL NOP Provisorio T180 SC': ('ACEITE LIMON', 'NOP', 'ACEITE'),
    'AEL NOP Provisorio T180 TUC': ('ACEITE LIMON', 'NOP', 'ACEITE'),
    'AEL Provisorio T180': ('ACEITE LIMON', 'Convencional', 'ACEITE'),
    'AEL UE Provisorio T180 SC': ('ACEITE LIMON', 'UE', 'ACEITE'),
    'AEL UE Provisorio T180 TUC': ('ACEITE LIMON', 'UE', 'ACEITE'),
    'AEN Agria Provisorio T180': ('ACEITE NARANJA AGRIA', 'Convencional', 'ACEITE'),
    'AEN NOP Provisorio T180': ('ACEITE NARANJA', 'NOP', 'ACEITE'),
    'AEN Provisorio T180': ('ACEITE NARANJA', 'Convencional', 'ACEITE'),
    'AEPP Provisorio T180': ('ACEITE POMELO ROSADO', 'Convencional', 'ACEITE'),
    'AEPW Provisorio T180': ('ACEITE POMELO BLANCO', 'Convencional', 'ACEITE'),
    'Cáscara Deshidratada de Limón CF-1 50 Kg': ('CF-1 LIMON', 'Convencional', 'FIBRA'),
    'Cáscara Deshidratada de Limón LF-19 50 Kg': ('LF-19 LIMON', 'Convencional', 'FIBRA'),
    'Cáscara Deshidratada de Naranja NOP CF-1 50 Kg': ('CF-1 NARANJA NOP', 'NOP', 'FIBRA'),
    'Cera de Limón T200 Kg': ('CERA DE LIMON', 'Convencional', 'OTROS'),
    'Concentrado de Aceite de Limón 5 Fold T180': ('ACEITE CONCENTRADO LIMON', 'Convencional', 'ACEITE'),
    'Concentrado de Aceite de Naranja 5 Fold T180': ('ACEITE CONCENTRADO NARANJA', 'Convencional', 'ACEITE'),
    'Jugo Clarificado B de Limón T200 Kg': ('JUGO LIMON', 'Convencional', 'JUGO CONCENTRADO'),
    'Jugo Clarificado de Limón 400 Gpl B23 Kg': ('JUGO LIMON 400 GPL', 'Convencional', 'JUGO CONCENTRADO'),
    'Jugo Clarificado de Limón 500 Gpl B25,5 Kg': ('JUGO LIMON 500 GPL', 'Convencional', 'JUGO CONCENTRADO'),
    'Jugo Clarificado de Limón 500 Gpl T260 Kg': ('JUGO LIMON 500 GPL', 'Convencional', 'JUGO CONCENTRADO'),
    'Jugo Clarificado de Naranja Agria T265 Kg': ('JUGO NARANJA AGRIA', 'Convencional', 'JUGO CONCENTRADO'),
    'Jugo Clarificado de Pomelo T260 Kg': ('JUGO POMELO', 'Convencional', 'JUGO CONCENTRADO'),
    'Jugo Concentrado B de Limón T200 Kg': ('JUGO LIMON', 'Convencional', 'JUGO CONCENTRADO'),
    'Jugo Concentrado Clarificado de Limón Alto Bx 300 Gpl T260 Kg': ('JUGO LIMON 300 GPL', 'Convencional', 'JUGO CONCENTRADO'),
    'Jugo Concentrado de Limón 400 Gpl B24,5 Kg': ('JUGO LIMON 400 GPL', 'Convencional', 'JUGO CONCENTRADO'),
    'Jugo Concentrado de Limón 500 Gpl B1425 Kg': ('JUGO LIMON 500 GPL', 'Convencional', 'JUGO CONCENTRADO'),
    'Jugo Concentrado de Limón 500 Gpl B25 Kg': ('JUGO LIMON 500 GPL', 'Convencional', 'JUGO CONCENTRADO'),
    'Jugo Concentrado de Limón UE 500 Gpl T260 Kg': ('JUGO LIMON 500 GPL', 'UE', 'JUGO CONCENTRADO'),
    'Jugo Concentrado de Naranja Clarificado Alto Bx T265': ('JUGO NARANJA', 'Convencional', 'JUGO CONCENTRADO'),
    'Jugo Concentrado de Naranja Turbio Alto Bx T265': ('JUGO NARANJA', 'Convencional', 'JUGO CONCENTRADO'),
    'Jugo Concentrado FR de Limon T200 Kg': ('JUGO LIMON', 'Convencional', 'JUGO CONCENTRADO'),
    'Terpeno de limón T180': ('TERPENOS LIMON', 'Convencional', 'ACEITE'),
    'Terpeno de naranja T180': ('TERPENOS NARANJA', 'Convencional', 'ACEITE'),
    'Jugo Clarificado de Limón 500 Gpl B25 Kg': ('JUGO LIMON 500 GPL', 'Convencional', 'JUGO CONCENTRADO'),
    'Aceite Esencial de Limón T47 Kg': ('ACEITE LIMON', 'Convencional', 'ACEITE'),
    'Terpeno de limón T47 Kg': ('TERPENOS LIMON', 'Convencional', 'ACEITE'),
    'Cáscara Deshidratada de Limón HF 20 Kg': ('HF', 'Convencional', 'FIBRA'),
    'Cáscara Deshidratada de Limón NOP CF-1 20 Kg': ('CF-1 LIMON NOP', 'NOP', 'FIBRA'),
    'xAceite de Semilla de Limón B20': ('ACEITE SEMILLA LIMON', 'Convencional', 'ACEITE'),
    'Aceite de Semilla de Limón T200 Lts': ('ACEITE SEMILLA LIMON', 'Convencional', 'ACEITE'),
    'Jugo NFC de Limón B20 Kg': ('NFC LIMON', 'Convencional', 'NFC'),
    'xAceite Esencial de Limón T 180 Kg.': ('ACEITE LIMON', 'Convencional', 'ACEITE'),
    'xAceite Esencial de Limón T40 Kg': ('ACEITE LIMON', 'Convencional', 'ACEITE'),
    'xAceite Esencial de Naranja T180 Kg': ('ACEITE NARANJA', 'Convencional', 'ACEITE'),
    'xAceite Esencial de Pomelo T180 Kg': ('ACEITE POMELO ROSADO', 'Convencional', 'ACEITE'),
    'xCáscara Deshidratada de Limón B20 Kg': ('CASCARA LIMON - A', 'Convencional', 'CASCARA'),
    'xCáscara Deshidratada de Limón B50 Kg': ('CASCARA LIMON - A', 'Convencional', 'CASCARA'),
    'xCáscara Deshidratada de Naranja B50 Kg': ('CASCARA NARANJA - A', 'Convencional', 'CASCARA'),
    'xJugo Clarificado de Pomelo T260 Kg': ('JUGO POMELO', 'Convencional', 'JUGO CONCENTRADO'),
    'xJugo Concentrado de Limón 400 GPL B1400 Kg.': ('JUGO LIMON 400 GPL', 'Convencional', 'JUGO CONCENTRADO'),
    'xJugo Concentrado de Limón 400 Gpl B1440 Kg': ('JUGO LIMON 400 GPL', 'Convencional', 'JUGO CONCENTRADO'),
    'xJugo Concentrado de Limón 400 GPL T250 Kg.': ('JUGO LIMON 400 GPL', 'Convencional', 'JUGO CONCENTRADO'),
    'xJugo Concentrado de Limón 500 Gpl T260 Kg': ('JUGO LIMON 500 GPL', 'Convencional', 'JUGO CONCENTRADO'),
    'xJugo Concentrado de Naranja T265 Kg': ('JUGO NARANJA', 'Convencional', 'JUGO CONCENTRADO'),
    'xJugo Concentrado de Pomelo T255 Kg': ('JUGO POMELO', 'Convencional', 'JUGO CONCENTRADO'),
    'xJugo Concentrado de Pomelo T265 Kg': ('JUGO POMELO', 'Convencional', 'JUGO CONCENTRADO'),
    'Jugo Concentrado FB de Limón T200 Kg': ('JUGO LIMON 400 GPL', 'Convencional', 'JUGO CONCENTRADO'),
    'Jugo Concentrado de Limón 400 Gpl B1100 Kg': ('JUGO LIMON 400 GPL', 'Convencional', 'JUGO CONCENTRADO'),
    'Jugo Concentrado de Limón 400 Gpl a Granel': ('JUGO LIMON 400 GPL', 'Convencional', 'JUGO CONCENTRADO'),
    'Aceite Esencial de Limón T100 Kg': ('ACEITE LIMON', 'Convencional', 'ACEITE'),
    'Jugo NFC de Limón Clarificado UE B20': ('NFC LIMON', 'NOP', 'NFC'),
    'xEsencia de Limón Fase Acuosa T200 Kg': ('ESENCIA LIMON', 'Convencional', 'ACEITE'),
    'Cáscara Deshidratada de Limón HF 60m 20kg': ('HF', 'Convencional', 'FIBRA'),
    'Cáscara Deshidratada de Limón LF-19 60m 20kg': ('LF-19 LIMON', 'Convencional', 'FIBRA'),
    'xEsencia de Limón Fase Oleosa T180 Kg': ('ESENCIA LIMON', 'Convencional', 'ACEITE'),
    'Anticipos por compra de fruta fresca': (None, None, None),
    'Gastos Bancarios': (None, None, None),
    'Gastos por Gestiones Comerciales': (None, None, None),
    'Gastos por Servicios Comerciales - Industria': (None, None, None),
    'Otros Ingresos': (None, None, None),
    'Reconocimiento por Cancelación de Ordenes de Compra año 2018': (None, None, None),
    'Recupero de Gastos': (None, None, None),
    'Recupero de Gastos de Comercialización': (None, None, None),
    'Reembolsos de Gastos por THC, BL ETC - PERÚ': (None, None, None),
    'Servicio de Flete Jcl': (None, None, None),
    'Servicio de Frio': (None, None, None),
    'Servicios Comerciales y Similares': (None, None, None),
    'Flete Marítimo': (None, None, None),
    'Jugo Concentrado de Limón NOP 500 Gpl T250 Kg': ('JUGO LIMON 500 GPL', 'NOP', 'JUGO CONCENTRADO'),
    'Jugo Concentrado de Limón 400 Gpl T250Kg': ('JUGO LIMON 400 GPL', 'Convencional', 'JUGO CONCENTRADO'),
    'Cáscara Deshidratada de Limón B60 20 Kg': ('CASCARA LIMON - A', 'Convencional', 'CASCARA'),
    'Aceite de Semilla de Limón T180 Kg': ('ACEITE SEMILLA LIMON', 'Convencional', 'ACEITE'),
    'Aceite Esencial de Limón T50 Kg': ('ACEITE LIMON', 'Convencional', 'ACEITE'),
    'Aceite Esencial de Pomelo P T50 Kg': ('ACEITE POMELO', 'Convencional', 'ACEITE'),
    'Terpeno de limón T180 Kg': ('TERPENOS LIMON', 'Convencional', 'ACEITE'),
    'Aceite de Semilla de Naranja B20 Lts': ('ACEITE SEMILLA NARANJA', 'Convencional', 'ACEITE'),
    'Cáscara Deshidratada de Limón NOP B50 Kg': ('CASCARA LIMON - A', 'NOP', 'CASCARA'),
    'Extracto de Limón L B20 Kg': ('EXTRACTO DE LIMON', 'Convencional', 'ACEITE'),
    'Jugo Concentrado de Limón 500 Gpl Balde 25 Kg': ('JUGO LIMON 500 GPL', 'Convencional', 'JUGO CONCENTRADO'),
    'Jugo en polvo de limón B20 kg': ('JUGO EN POLVO', 'Convencional', 'JUGO CONCENTRADO'),
    'Jugo Concentrado de Limón 500 Gpl Bidon25 Kg': ('JUGO LIMON 500 GPL', 'Convencional', 'JUGO CONCENTRADO'),
    'Jugo concentrado de Limón 500 GPL 260 Kg': ('JUGO LIMON 500 GPL', 'Convencional', 'JUGO CONCENTRADO'),
    'Aceite de Semilla de Naranja B20': ('ACEITE SEMILLA NARANJA', 'Convencional', 'ACEITE'),
    'Terpeno de naranja T180 Kg': ('TERPENOS NARANJA', 'Convencional', 'ACEITE'),
    'Ajuste por Calidad Aceite Esencial de Limón T180 Kg': ('ACEITE LIMON', 'Convencional', 'ACEITE'),
    'Demurrage en el Exterior': (None, None, None),
    'Descuentos/Bonific Obtenidos': (None, None, None),
    'Servicio de Flete Ael': (None, None, None),
    'Cáscara Deshidratada de Limón NOP CF-1 140m 20 Kg': ('CF-1 LIMON NOP', 'NOP', 'FIBRA'),
    'Cáscara Deshidratada de Limón CF-1 140m 20 kg': ('CF-1 LIMON', 'Convencional', 'FIBRA'),
    'Aceite Esencial de Limón UE T180 Kg': ('ACEITE LIMON', 'NOP', 'ACEITE'),
    'Aceite Esencial Limón Verde T180 Kg': ('ACEITE LIMON', 'Convencional', 'ACEITE'),
    'Aceite Semilla Limón a Granel': ('ACEITE SEMILLA LIMON', 'Convencional', 'ACEITE'),
    'AE Limon NOP Granel Tk 8100 TUC': ('ACEITE LIMON', 'NOP', 'ACEITE'),
    'AEL Prov Centrifugado TP T180': ('ACEITE LIMON', 'Convencional', 'ACEITE'),
    'AEL Prov Fracción A TP T180': ('ACEITE PERU', 'Convencional', 'ACEITE'),
    'AEL Prov Fracción B TP T180': ('ACEITE PERU', 'Convencional', 'ACEITE'),
    'AEL Prov Fracción C TP T180': ('ACEITE PERU', 'Convencional', 'ACEITE'),
    'AEM Provisorio T180': ('ACEITE MANDARINA', 'Convencional', 'ACEITE'),
    'AEN Tangerina Provisorio T180': ('ACEITE NARANJA', 'Convencional', 'ACEITE'),
    'AEP NOP Provisorio T180': ('ACEITE POMELO', 'NOP', 'ACEITE'),
    'AEP P Provisorio T180': ('ACEITE POMELO', 'Convencional', 'ACEITE'),
    'AEP W Provisorio T180': ('ACEITE POMELO', 'Convencional', 'ACEITE'),
    'Cáscara Deshidratada de Mandarina B50 Kg': ('CASCARA MANDARINA - A', 'Convencional', 'CASCARA'),
    'CD Limon Desolventizador CF-1 150 Kg': ('CF-1 LIMON', 'Convencional', 'FIBRA'),
    'CD Limon LF19 Bin 150 Kg': ('LF-19 LIMON', 'Convencional', 'FIBRA'),
    'Esencia de Limón Fase Oleosa TP T180': ('ESENCIA LIMON', 'Convencional', 'ACEITE'),
    'Jugo Concentrado de Limón 400 Gpl B25 Kg': ('JUGO LIMON 400 GPL', 'Convencional', 'JUGO CONCENTRADO'),
    'Jugo Concentrado de Mandarina Alto Bx T265': ('JUGO MANDARINA', 'Convencional', 'JUGO CONCENTRADO'),
    'Jugo Concentrado de Mandarina T265 Kg': ('JUGO MANDARINA', 'Convencional', 'JUGO CONCENTRADO'),
    'Jugo Concentrado Top de Naranja T250 Kg': ('JUGO NARANJA', 'Convencional', 'JUGO NARANJA TOP'),
    'Jugo NFC Aséptico de Limón NOP B1000 Kg': ('NFC LIMON', 'NOP', 'NFC'),
    'Jugo NFC de Naranja TC 200 Kg': ('NFC NARANJA', 'Convencional', 'NFC'),
    'Jugo NFC de Limón Clarificado UE T200': ('NFC LIMON', 'NOP', 'NFC'),
    'Descuentos/Bonific Otorg Sobre Ventas Aceite de Naranja': ('ACEITE LIMON', 'Convencional', 'ACEITE'),
    'Descuentos/Bonific Otorg Sobre Ventas Cáscara Deshidratada de Limón': ('CASCARA LIMON - A', 'Convencional', 'CASCARA'),
    'Descuentos/Bonific Otorg Sobre Ventas Cáscara Deshidratada de Naranja': ('CASCARA NARANJA - A', 'Convencional', 'CASCARA'),
    'Gastos de puerto en el exterior': (None, None, None),
    'ORG Grapefr Star Ruby 16KG PE cl25 II CT': (None, None, None),
    'ORG Grapefr Star Ruby 16KG PE cl30 II CT': (None, None, None),
    'Aceite de Semilla de Naranja T200 Lts': ('ACEITE SEMILLA NARANJA', 'Convencional', 'ACEITE'),
    'Ajuste por Cambio Documental': (None, None, None),
    'Concentrado de Aceite de Naranja 5 Fold B19K': ('ACEITE LIMON', 'Convencional', 'ACEITE'),
    'Concentrado de Aceite de Limón 5 Fold B19K': ('ACEITE LIMON', 'Convencional', 'ACEITE'),
    'Aceite de Semilla de Limón T180 Kgs': ('ACEITE SEMILLA LIMON', 'Convencional', 'ACEITE'),
}


# Nombres de columna TAL CUAL el Excel (hoja Producto-Segmento).
COLUMNAS = ["PRODUCTO", "Fam-Esp 2", "Segmento", "Segmento 2"]


def tabla() -> list[dict]:
    """La tabla Producto-Segmento como filas, igual que en el Excel.

    Se expone como un cajón aparte del JSON para que Marco la materialice en
    su propia tabla (no se cruza con las otras APIs).
    """
    return [
        {"PRODUCTO": producto, "Fam-Esp 2": fam_esp,
         "Segmento": segmento, "Segmento 2": segmento_2}
        for producto, (fam_esp, segmento, segmento_2) in PRODUCTO_SEGMENTO.items()
    ]
